from fpdf import FPDF
from datetime import datetime

# -------------------------------------------------
# Generate AI Resume Report as PDF
# -------------------------------------------------
def generate_pdf_report(details, ai_feedback, ats_score):
    """
    Generates a clean PDF report from resume analysis and AI feedback.
    Returns the PDF bytes.
    """
    pdf = FPDF()
    pdf.add_page()
    
    # Title Section
    pdf.set_font("Arial", "B", 18)
    pdf.cell(200, 10, txt="AI Resume Analysis Report", ln=True, align="C")
    pdf.ln(10)

    # Date
    pdf.set_font("Arial", "", 12)
    pdf.cell(200, 10, txt=f"Generated on: {datetime.now().strftime('%d %B %Y, %I:%M %p')}", ln=True)
    pdf.ln(10)

    # ATS Score
    pdf.set_font("Arial", "B", 14)
    pdf.cell(200, 10, txt=f"📊 ATS Score: {ats_score}/100", ln=True)
    pdf.ln(10)

    # Basic Details
    pdf.set_font("Arial", "B", 14)
    pdf.cell(200, 10, txt="📋 Extracted Details:", ln=True)
    pdf.set_font("Arial", "", 12)
    for key, value in details.items():
        pdf.multi_cell(0, 8, f"{key}: {value}")
    pdf.ln(5)

    # AI Feedback Section
    pdf.set_font("Arial", "B", 14)
    pdf.cell(200, 10, txt="🧠 AI Feedback & Suggestions:", ln=True)
    pdf.set_font("Arial", "", 12)
    pdf.multi_cell(0, 8, ai_feedback)
    pdf.ln(10)

    # Footer
    pdf.set_font("Arial", "I", 10)
    pdf.multi_cell(0, 6, "Generated by AI Resume Ranker & Career Coach — Kollu Balavardhan © 2025")

    # Return PDF bytes
    return pdf.output(dest="S").encode("latin-1")
